image: php:5.6

stages:
  - test
  - publish

before_script:
  - apt-get update -qq

tests:
  stage: test
  script:
    # Install some Drupal dependencies.
    - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq sqlite3 php5-sqlite php5-json php5-curl > /dev/null
    # php5-gd doesn't appear to be sufficient under Docker, so these extra
    # packages and steps appear to be necessary.
    - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq php5-gd libjpeg-dev libpng-dev libfreetype6-dev > /dev/null
    - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ > /dev/null
    - docker-php-ext-install gd > /dev/null
    # Drumkit is installed as a submodule.
    - git submodule update --init
    # Bootstrap Drumkit.
    - . d
    # Install a Drupal site, dowload Behat, and run some tests.
    - make drupal
    - make behat
    - make drupal-tests CURRENT_TEST=features/openproducer.feature

notify:irker:failure:
  stage: test
  script:
    - "make irker-message IRKER_MESSAGE='FAILURE -- A recent build of OpenProducer failed! See: https://gitlab.com/openproducer/openproducer/builds'"
  when: on_failure
  only:
    - 8.x-0.0.x

notify:irker:success:
  stage: test
  script:
    - "make irker-message IRKER_MESSAGE='SUCCESS -- A recent build of OpenProducer succeeded! See: https://gitlab.com/openproducer/openproducer/builds'"
  when: on_success
  only:
    - 8.x-0.0.x

pages:
  stage: publish
  script:
    # Install MkDocs.
    - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq python-pip
    - pip install mkdocs
    # Build our documentation site.
    - mkdocs build --clean -d public/
  artifacts:
    paths:
      - public
  only:
    - 8.x-0.0.x
