image: php:5.6

stages:
  - test
  - notify
  - publish

before_script:
  - apt-get update -qq
  - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq git netcat > /dev/null
  # Drumkit is installed as a submodule.
  - git submodule update --init
  # Bootstrap Drumkit.
  - . d

tests:
  stage: test
  script:
    # Install some Drupal dependencies.
    - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq sqlite3 php5-sqlite php5-json php5-curl > /dev/null
    # php5-gd doesn't appear to be sufficient under Docker, so these extra
    # packages and steps appear to be necessary.
    - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq php5-gd libjpeg-dev libpng-dev libfreetype6-dev > /dev/null
    - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ > /dev/null
    - docker-php-ext-install gd > /dev/null
    # Install a Drupal site, dowload Behat, and run some tests.
    - make drupal
    - make behat
    - make drupal-tests

notify:irker:failure:
  stage: notify
  script:
    - "make irker-message IRKER_MESSAGE='Build on $CI_BUILD_REF_NAME failed! Commit $(git log -1 --oneline) See <https://gitlab.com/openproducer/$(basename $PWD)/commit/$CI_BUILD_REF/builds>'"
  when: on_failure
  # Tests for work-in-progress features are expected to fail, so there's no need to spam the IRC channel.
  only:
    - /^8.x-.*$/

notify:irker:success:
  stage: notify
  script:
    - "make irker-message IRKER_MESSAGE='Build on $CI_BUILD_REF_NAME succeeded! Commit $(git log -1 --oneline) See <https://gitlab.com/openproducer/$(basename $PWD)/commit/$CI_BUILD_REF/builds>'"
  when: on_success

pages:
  stage: publish
  script:
    # Install MkDocs.
    - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq python-pip
    - pip install mkdocs
    # Build our documentation site.
    - mkdocs build --clean -d public/
  artifacts:
    paths:
      - public
  when: on_success
  only:
    - 8.x-0.0.x
