site_name: OpenProducer
repo_url: https://gitlab.com/openproducer/openproducer
theme: readthedocs
site_favicon: '_images/favicon.ico'
site_dir: '/tmp/openproducer_docs/_site'
markdown_extensions:
- codehilite:
    noclasses: True
    pygments_style: emacs
extra_css:
- '_css/menu.css'
- '_css/term.css'
- '_css/style.css'
pages:
- 'Home': 'index.md'
- 'Configuration': 'configuration.md'
- 'Hosting': 'hosting.md'
- 'Development': 'development.md'
- 'Documentation': 'documentation.md'
